### ISSUE TITLE
Additional methods required

### ISSUE THREAD

**Issue by edgarsselis** [testdevlab/TestUI#45]
Following methods in TestUI required (taken from Selenide):

1. element.selectOptionByValue();
2. element.findBy(Condition.value());
3. element.parent();

**Comment by alvarolaserna** [comment]
EE(locator).findByValue() and E(locator).selectElementByValue(...values) are implemented under 12.1>=
parent method is still in progress, but not sure whether will or not be implemented in a near future. 

You can reopen a new ticket for the parent() method, or if you find any solution for Appium driver to search for that parent, Im happy to see contributions.
