### ISSUE TITLE
Add .executeScript() function to execute JS scripts

### ISSUE THREAD

**Issue by Kirils-Podgalskis** [testdevlab/TestUI#91]
Current version of TestUI doesn't have its own `.executeScript` function. More over, following approach doesn't return any value at all:
```
((JavascriptExecutor) WebDriverRunner.getWebDriver()).executeScript(
    "2+2"
);
```

**Comment by alvarolaserna** [comment]
I don't think that has to return anything, to check that the executeScript works, you can try this:

```
((JavascriptExecutor) WebDriverRunner.getWebDriver()).executeScript("location.reload()");
```

This will reload the page, and it works

**Comment by Kirils-Podgalskis** [comment]
Yes, it works, but does not return anything

**Comment by alvarolaserna** [comment]
Im afraid this is direct implementation from Selenium, so if you are looking for it to return something, you will have to raise the issue on the Selenium repository. Unless you can prove me that this is happening only with this implementation.

**Comment by alvarolaserna** [comment]
Closing issue as it is not related to the repo, but Selenium itself
